/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MisCitasRouteImport } from './routes/mis-citas'
import { Route as MecanicoRouteImport } from './routes/mecanico'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmacionRouteImport } from './routes/confirmacion'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MisCitasRoute = MisCitasRouteImport.update({
  id: '/mis-citas',
  path: '/mis-citas',
  getParentRoute: () => rootRouteImport,
} as any)
const MecanicoRoute = MecanicoRouteImport.update({
  id: '/mecanico',
  path: '/mecanico',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionRoute = ConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/dashboard': typeof DashboardRoute
  '/mecanico': typeof MecanicoRoute
  '/mis-citas': typeof MisCitasRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/dashboard': typeof DashboardRoute
  '/mecanico': typeof MecanicoRoute
  '/mis-citas': typeof MisCitasRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/dashboard': typeof DashboardRoute
  '/mecanico': typeof MecanicoRoute
  '/mis-citas': typeof MisCitasRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/confirmacion'
    | '/dashboard'
    | '/mecanico'
    | '/mis-citas'
    | '/perfil'
    | '/registro'
    | '/servicios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/confirmacion'
    | '/dashboard'
    | '/mecanico'
    | '/mis-citas'
    | '/perfil'
    | '/registro'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/confirmacion'
    | '/dashboard'
    | '/mecanico'
    | '/mis-citas'
    | '/perfil'
    | '/registro'
    | '/servicios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfirmacionRoute: typeof ConfirmacionRoute
  DashboardRoute: typeof DashboardRoute
  MecanicoRoute: typeof MecanicoRoute
  MisCitasRoute: typeof MisCitasRoute
  PerfilRoute: typeof PerfilRoute
  RegistroRoute: typeof RegistroRoute
  ServiciosRoute: typeof ServiciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-citas': {
      id: '/mis-citas'
      path: '/mis-citas'
      fullPath: '/mis-citas'
      preLoaderRoute: typeof MisCitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mecanico': {
      id: '/mecanico'
      path: '/mecanico'
      fullPath: '/mecanico'
      preLoaderRoute: typeof MecanicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion': {
      id: '/confirmacion'
      path: '/confirmacion'
      fullPath: '/confirmacion'
      preLoaderRoute: typeof ConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfirmacionRoute: ConfirmacionRoute,
  DashboardRoute: DashboardRoute,
  MecanicoRoute: MecanicoRoute,
  MisCitasRoute: MisCitasRoute,
  PerfilRoute: PerfilRoute,
  RegistroRoute: RegistroRoute,
  ServiciosRoute: ServiciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
